FROM python:3.12-slim-bookworm

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py /app/main.py

EXPOSE 2375
CMD ["python", "-u", "/app/main.py"]
